// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DiscussedApi.Data.Identity;

#nullable disable

namespace DiscussedApi.Migrations
{
    [DbContext(typeof(ApplicationIdentityDBContext))]
    [Migration("20241017111016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PFMSApi.Models.Account", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Number"));

                    b.Property<decimal>("BankBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("BankType")
                        .HasColumnType("int");

                    b.Property<string>("ChangePercentage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MonthSpending")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Number");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
